spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/blog
    username: root
    password: root
  thymeleaf:
    cache: false
    check-template-location: true
    mode: html